version: "3"
services:
    app:
        working_dir: /var/www/blog
        build: .
        volumes:
            - ./blog:/var/www/blog
        links:
            - db
        depends_on:
            - db
        entrypoint: ./entrypoint.sh
        environment: 
            - DB_DATABASE=$DB_NAME
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
    nginx:
        working_dir: /var/www
        image: nginx
        volumes:
            - ./blog:/var/www/lumen
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - app
        ports:
            - "8081:80"
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=$DB_NAME
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
        volumes:
            - "./data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
